name: anandownload
description: "a lite download tools"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_smart_dialog: ^4.9.8+5
  logger: ^2.6.0
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  dio: ^5.8.0+1
  window_manager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
